console.log(
  JSON.parse(
    [
      {
         "label":"count",
         "type":"number",
      },
      {
         "label":"is checked",
         "type":"checkbox",
      },
      {
         "label":"caption",
         "type":"text",
      },
      {
         "label":"description",
         "type":"textarea",
      },
    ]
  )
)